import Head from 'next/head';
import { GetStaticProps, NextPage } from 'next';
import Layout from '@/components/Layout';
import TransfersList from '@/components/TransfersList';
import { ITransfer } from '@/models/Transfer';

type PageProps = {
  transfers: ITransfer[] | [];
} & NextPage;

const Home = ({ transfers }: PageProps) => {
  return (
    <>
      <Head>
        <title>Transfers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="flex flex-col justify-center p-[20px] pt-[80px] md:p-[31px] md:pl-[112px] md:pt-[102px]">
          <TransfersList transfers={transfers} />
        </section>
      </Layout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  /**
   * This function runs only on serverside at build time
   * so it is safe to use env variables and sensitive info
   * like API keys here.
   */
  const URL =
    process.env.NODE_ENV === 'development'
      ? process.env.DEV_URL
      : process.env.PRODUCTION_URL;

  const res = await fetch(`${URL}/api/transfers`);

  const { transfers } = await res.json();

  return {
    props: {
      transfers: transfers || [],
    },
    revalidate: 60, // Re-hydrates every 60s the props in case they changed
  };
};

export default Home;
