import Head from 'next/head';
import Layout from '@/components/Layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Transfers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="p-[30px] pl-[121px]">
          <h2 className="font-semibold text-brand-blue">Transfers</h2>
        </section>
      </Layout>
    </>
  );
}
