import Head from 'next/head';
import { GetStaticProps, NextPage } from 'next';
import Layout from '@/components/Layout';
import TransfersList from '@/components/TransfersList';
import { ITransfer } from '@/models/Transfer';

type PageProps = {
  transfers: ITransfer[];
} & NextPage;

export default function Home({ transfers }: PageProps) {
  return (
    <>
      <Head>
        <title>Transfers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="p-[31px] pl-[112px]">
          <TransfersList transfers={transfers} />
        </section>
      </Layout>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('http://127.0.0.1:3000/api/transfers');

  const transfers: ITransfer[] = await res.json();

  return {
    props: {
      transfers,
    },
  };
};
